// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBXQaDQCXvVGIMlK2j4pPREKPfd-4EqNC4',
    appId: '1:16391671579:web:dff622b1e635d852ba8dbe',
    messagingSenderId: '16391671579',
    projectId: 'augment-ec748',
    authDomain: 'augment-ec748.firebaseapp.com',
    storageBucket: 'augment-ec748.firebasestorage.app',
    measurementId: 'G-CF02CN3943',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDjW_D6u5mtWWesiHPyCsZFhpgcf0eeqLM',
    appId: '1:16391671579:android:2f3df04ae1ad8afbba8dbe',
    messagingSenderId: '16391671579',
    projectId: 'augment-ec748',
    storageBucket: 'augment-ec748.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAgW7BimMGk2B47_A_MqpAFaM6m5UMHuDM',
    appId: '1:16391671579:ios:1732eb7e1bd77c24ba8dbe',
    messagingSenderId: '16391671579',
    projectId: 'augment-ec748',
    storageBucket: 'augment-ec748.firebasestorage.app',
    iosBundleId: 'com.example.augmentApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAgW7BimMGk2B47_A_MqpAFaM6m5UMHuDM',
    appId: '1:16391671579:ios:1732eb7e1bd77c24ba8dbe',
    messagingSenderId: '16391671579',
    projectId: 'augment-ec748',
    storageBucket: 'augment-ec748.firebasestorage.app',
    iosBundleId: 'com.example.augmentApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBXQaDQCXvVGIMlK2j4pPREKPfd-4EqNC4',
    appId: '1:16391671579:web:717e499d54164f17ba8dbe',
    messagingSenderId: '16391671579',
    projectId: 'augment-ec748',
    authDomain: 'augment-ec748.firebaseapp.com',
    storageBucket: 'augment-ec748.firebasestorage.app',
    measurementId: 'G-0B1JJPMEK2',
  );
}
